.PHONY: check-style

check-style:
	@echo checking style of module: core ...
	flake8 core/
	@echo checking style of module: gui ...
	flake8 gui/
	@echo checking style of module: models ...
	flake8 models/