.PHONY: check-style

check-style:
	@echo checking style of module: core ...
	flake8 core/
	@echo checking style of module: gtkclient ...
	flake8 gtkclient/
	@echo checking style of module: gtkclient.gui ...
	flake8 gtkclient/gui/
	@echo checking style of module: models ...
	flake8 models/