#!/usr/bin/python3

""" Entry point. """

import gi
gi.require_version('Gtk', '3.0')
from gi.repository.Gtk import main, main_quit
from gi.repository.Gtk import Builder

from gtkclient.object_factory import GtkObjectFactory
from gtkclient.gui.console import Console
from gtkclient.gui.dialogs import CreateObjectDialog
from gtkclient.gui.main_window import MainWindow
from gtkclient.gui.viewport import ViewPort

from models.window import Window

from wml import WML_Interpreter


def init_client():
    builder = Builder()
    builder.add_from_file("gtkclient/glade/z_gui_layout.glade")

    # Dont need anything
    window = Window()
    display_file = {}

    # Glade
    drawing_area = builder.get_object("viewport_drawing_area")
    store = builder.get_object("object_list_store")
    treeview = builder.get_object("object_list")

    # Need something
    viewport = ViewPort(drawing_area, window, display_file)
    obj_factory = GtkObjectFactory(store, viewport, display_file)
    wml_interpreter = WML_Interpreter(obj_factory, viewport, display_file)
    console = Console(builder.get_object("console_text_view"), wml_interpreter)
    create_obj_dialog = CreateObjectDialog(
        builder.get_object("create_object_dialog"),
        builder.get_object("create_object_dialog_name_field"),
        builder.get_object("create_object_dialog_points_field"),
        builder.get_object("create_object_dialog_color_field"),
        obj_factory,
        wml_interpreter)
    main_window = MainWindow(create_obj_dialog, obj_factory, treeview,
                            viewport,
                            window,
                            display_file,
                            builder.get_object("degrees_entry"),
                            builder.get_object("point_entry"),
                            builder.get_object("step_entry"),
                            builder.get_object("center_of_world_radio_button"))

    # Handlers
    handlers = { "on_destroy": main_quit }
    handlers.update(main_window.handlers)
    handlers.update(create_obj_dialog.handlers)
    handlers.update(viewport.handlers)
    builder.connect_signals(handlers)

    builder.get_object("main_window").show_all()
    main()

if __name__ == "__main__":
    init_client()