#!/usr/bin/python3

""" Entry point. """

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

from gui.main_window import MainWindow


# TODO (first release):
# define what is logged and what is not
# Deselect rows
# Dont allow things to resize?
# move logic away from interface
# factory pattern
# python enums
# fix console
# requirements.txt?

# TODO (second release):
# Rotation of world

# Future:
# Fix requirements.txt
# Typed python?

if __name__ == "__main__":
    main_window = MainWindow()
    main_window.show()
    Gtk.main()
